### ISSUE TITLE
Que fim deu esse Curso? 

### ISSUE THREAD

**Issue by fabiovila** [hallpaz/cda2020#1]
Olá colega, que fim deu esse curso? Lembro que me inscrevi e de repente sumiu o conteúdo. Tinha esquecido disso, então achei seu repositório e lembrei que sumiu tudo do nada. Aliás, depois daquele dia o site do IMPA ficou pouco acessível, muitos 404. Ficou meio que fechado.

**Comment by hallpaz** [comment]
Oi, Fábio, o curso foi cancelado por indisponibilidade do professor. A Coordenação de Ensino enviou um e-mail em 25 de agosto de 2020 comunicando os inscritos.
